export const USER_LOGIN_SUBMITTED = 'USER_LOGIN_SUBMITTED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_REQUEST_SUCCESS';
export const USER_LOGIN_REQUEST_FAILURE = 'USER_LOGIN_REQUEST_FAILURE';

export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_REQUEST_SUCCESS = 'USER_REGISTRATION_REQUEST_SUCCESS';
export const USER_REGISTRATION_REQUEST_FAILURE = 'USER_REGISTRATION_REQUEST_FAILURE';